### ISSUE TITLE
Fails for batch size other than 1

### ISSUE THREAD

**Issue by pzpzpzp2** [NUS-HPC-AI-Lab/VideoSys#104]
https://github.com/NUS-HPC-AI-Lab/OpenDiT/blob/9ca54720f3aa4c3a20c642059be63d61308b1bf1/tests/test_fused_modulate.py#L7
fused_modulate does not work for batch sizes other than 1

**Comment by oahzxl** [comment]
get it. will look into this problem. thanks for your feedback

**Comment by oahzxl** [comment]
close due to outdated
