### ISSUE TITLE
Loss become nan after several epoches

### ISSUE THREAD

**Issue by canqin001** [NUS-HPC-AI-Lab/VideoSys#107]
Thank you for the amazing open-source project! I recently applied this code to train a model on ucf101, but the loss becomes nan after several epochs. Does anyone have similar problems? Are there any suggestions? Thanks!

![Screenshot 2024-03-17 at 4 06 11 PM](https://github.com/NUS-HPC-AI-Lab/OpenDiT/assets/46471476/c5e56f4f-8c4b-4943-912f-6ba06c6f644e)

**Comment by kwonminki** [comment]
After the Open-Sora update, --enable_flashattn occurs NaN loss on my side. @oahzxl

**Comment by oahzxl** [comment]
thats weird. have you used bf16? we have not met such problem in training.

**Comment by oahzxl** [comment]
and what global batch size are you using

**Comment by kwonminki** [comment]
Hi. 
I tried 1. disable modulate kernel 2. use bf16 3. grad clip; and all possible other things.
And only I disabled the flashattn, loss was not NaN.

I used a global batch of around 8(512x512) and 32(256x256).

+ My cuda is 12.4 
I think it could be the problem.

**Comment by oahzxl** [comment]
close due to inactive
