### ISSUE TITLE
The generated videos are shaking and unstable.

### ISSUE THREAD

**Issue by nankepan** [NUS-HPC-AI-Lab/VideoSys#122]
I trained an opensora model with webvid. The generated videos are shaking and unstable. Can you give me some reasons or suggestions？Is there some training tricks?

https://github.com/NUS-HPC-AI-Lab/OpenDiT/assets/82510548/8bb900e6-3ae8-4b82-b65c-a82e75d795f7

https://github.com/NUS-HPC-AI-Lab/OpenDiT/assets/82510548/ed88fa4a-fac5-40ac-933b-dd1c82cf7099

https://github.com/NUS-HPC-AI-Lab/OpenDiT/assets/82510548/f8a82ced-0ddd-4235-9e68-fe970e140dbd

**Comment by Edwardmark** [comment]
I test the open-sourced checkpoint the repo provided is unstable and shaking too. Is there anything missing?
I run the demo using:
torchrun --standalone --nproc_per_node=8 scripts/opensora/sample_opensora.py \
    --model_time_scale 1 \
    --model_space_scale 1 \
    --image_size 512 512 \
    --num_frames 80 \
    --fps 8 \
    --dtype fp16 \
    --sequence_parallel_size 8 \
    --enable_flashattn \
    --enable_layernorm_kernel \
    --text_speedup \
    --model_pretrained_path ./ckpt/OpenSora-v1-HQ-16x512x512.pth

**Comment by oahzxl** [comment]
close due to inactive

**Comment by ZTzxj** [comment]
> I trained an opensora model with webvid. The generated videos are shaking and unstable. Can you give me some reasons or suggestions？Is there some training tricks?
> 
>  sample_0.2.mp4 
>  sample_1.2.mp4 
>  sample_2.2.mp4

Hi, would like to trouble you to ask if you can post the webvid.csv file, the website I accessed related to it's dataset is currently down.

**Comment by nankepan** [comment]
> > I trained an opensora model with webvid. The generated videos are shaking and unstable. Can you give me some reasons or suggestions？Is there some training tricks?
> > sample_0.2.mp4
> > sample_1.2.mp4
> > sample_2.2.mp4
> 
> Hi, would like to trouble you to ask if you can post the webvid.csv file, the website I accessed related to it's dataset is currently down.

https://huggingface.co/datasets/TempoFunk/webvid-10M/tree/main

**Comment by ZTzxj** [comment]
> > > I trained an opensora model with webvid. The generated videos are shaking and unstable. Can you give me some reasons or suggestions？Is there some training tricks?
> > > sample_0.2.mp4
> > > sample_1.2.mp4
> > > sample_2.2.mp4
> > 
> > 
> > Hi, would like to trouble you to ask if you can post the webvid.csv file, the website I accessed related to it's dataset is currently down.
> 
> https://huggingface.co/datasets/TempoFunk/webvid-10M/tree/main

Thank you so much.
