### ISSUE TITLE
should nproc-per-node equals to sequence_parallel_size?

### ISSUE THREAD

**Issue by Edwardmark** [NUS-HPC-AI-Lab/VideoSys#126]
Great work. I have a question, should nproc-per-node equals to sequence_parallel_size when do open-sora inference using DSP?
Thanks in advance.

**Comment by oahzxl** [comment]
sp size should be as small as possible

**Comment by Edwardmark** [comment]
@oahzxl why sp size should be as small as possible?

**Comment by oahzxl** [comment]
because the essense of sequence parallel is to accomodate long sequence at the cost of extra communication cost. so if memory is enough, keep it low
