### ISSUE TITLE
For self implemented DiT, how to adapt PAB?

### ISSUE THREAD

**Issue by xiaocaijiayou** [NUS-HPC-AI-Lab/VideoSys#145]
Thanks a lot for sharing amazing work for DiT speed up. 

For self-implemented DiT, how to adapt PAB to make it work?

Thank you!

**Comment by oahzxl** [comment]
our code is not complicated. i hope these two files can help you

https://github.com/NUS-HPC-AI-Lab/OpenDiT/blob/master/opendit/core/pab_mgr.py
https://github.com/NUS-HPC-AI-Lab/OpenDiT/blob/ede0f32a3813f8674fa8231afe6630d05248278f/opendit/models/opensora/stdit3.py#L104

**Comment by xiaocaijiayou** [comment]
@oahzxl Thank you for your reply!
