### ISSUE TITLE
Question about DSP implementation details of opensora

### ISSUE THREAD

**Issue by xiaocaijiayou** [NUS-HPC-AI-Lab/VideoSys#146]
Quite confused, about DSP implementation of opensora, why is the dynamic switch only in temporal STDiT3Block? https://github.com/NUS-HPC-AI-Lab/OpenDiT/blob/ede0f32a3813f8674fa8231afe6630d05248278f/opendit/models/opensora/stdit3.py#L141-L152

Looking forward to your reply! Thank you.

**Comment by oahzxl** [comment]
because other parts are all independent of temporal dimension. so we only need to do switch for temporal attention

**Comment by xiaocaijiayou** [comment]
Thank you for your reply!
