### ISSUE TITLE
Benchmark time on H100

### ISSUE THREAD

**Issue by yossigandelsman** [NUS-HPC-AI-Lab/VideoSys#149]
Hi, 
I loved your work! 

I am trying to repeat the experiments you had on 8xH100s. 
When I run your codebase with `./scripts/opensora/sample_pab.sh` (after following the installation instructions), and change the number of frames in `configs/opensora/sample_pab.yaml` to 192, it takes around 9 seconds to sample a video. 
In your blog, you show that it takes around 4 seconds, so I am not sure what is the source for the difference in performance.
Will you be able to provide the exact parameters and script to reach the same performance as you reported? 

Thank you very much, 
Yossi

**Comment by oahzxl** [comment]
we use torch2.3 and cuda12.1, and skip the first cold start iter.

**Comment by oahzxl** [comment]
oh sorry for the mistake. the caption for the video in the blog is wrong. it should be 82 frames. you can refer to speedup section for correct speed.
