### ISSUE TITLE
How to obtain the mtrics of PAB

### ISSUE THREAD

**Issue by LiewFeng** [NUS-HPC-AI-Lab/VideoSys#172]
PAB is a really useful work and I wonder how obtain the mtrics of PAB. Thanks a lot!

**Comment by oahzxl** [comment]
do you mean the evaluation results? it's in the eval dir

**Comment by LiewFeng** [comment]
Yes. I notice the files in the eval dir but there is no instruction file and  could you provide more detailed instructions? Thanks!

**Comment by oahzxl** [comment]
sure will soon

**Comment by oahzxl** [comment]
guide for eval is updated now: https://github.com/NUS-HPC-AI-Lab/VideoSys/blob/master/eval/pab/README.md

**Comment by oahzxl** [comment]
currently torch already support flash attention. so we dont require to install flashattn manually.
