### ISSUE TITLE
OpenSora - Support for 720p and longer video (4+ seconds) ?

### ISSUE THREAD

**Issue by JC1DA** [NUS-HPC-AI-Lab/VideoSys#173]
Hi,
First of all, thanks for your great work.

I have done some testings with Open-Sora and it seems working great with default configuration (480p with 2 secs video). 
How ever, I ran into missing keys issue when I changed the config to 720p or longer video length (102 frames instead of 51).

[rank0]: Traceback (most recent call last):
[rank0]:   File "/data1/VideoSys/examples/open_sora/sample.py", line 27, in <module>
[rank0]:     run_pab()
[rank0]:   File "/data1/VideoSys/examples/open_sora/sample.py", line 21, in run_pab
[rank0]:     video = engine.generate(prompt, resolution="720p", num_frames=102, aspect_ratio="16:9", refs=img_path, ms="0", aes=6.5, flow=3, condition_frame_length=7).video[0]
[rank0]:   File "/data1/VideoSys/videosys/core/engine.py", line 104, in generate
[rank0]:     return self._run_workers("generate", *args, **kwargs)[0]
[rank0]:   File "/data1/VideoSys/videosys/core/engine.py", line 95, in _run_workers
[rank0]:     driver_worker_output = driver_worker_method(*args, **kwargs)
[rank0]:   File "/home/jc1da/anaconda3/envs/opensorav2/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/data1/VideoSys/videosys/models/open_sora/pipeline.py", line 396, in generate
[rank0]:     samples = self.scheduler.sample(
[rank0]:   File "/data1/VideoSys/videosys/models/open_sora/rflow.py", line 253, in sample
[rank0]:     output = model(z_in, t, all_timesteps, **model_args)
[rank0]:   File "/home/jc1da/anaconda3/envs/opensorav2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/jc1da/anaconda3/envs/opensorav2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/data1/VideoSys/videosys/models/open_sora/stdit3.py", line 520, in forward
[rank0]:     x = auto_grad_checkpoint(
[rank0]:   File "/data1/VideoSys/videosys/models/open_sora/utils.py", line 179, in auto_grad_checkpoint
[rank0]:     return module(*args, **kwargs)
[rank0]:   File "/home/jc1da/anaconda3/envs/opensorav2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/jc1da/anaconda3/envs/opensorav2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/data1/VideoSys/videosys/models/open_sora/stdit3.py", line 199, in forward
[rank0]:     broadcast_mlp, self.mlp_count, broadcast_next, skip_range = if_broadcast_mlp(
[rank0]:   File "/data1/VideoSys/videosys/core/pab_mgr.py", line 234, in if_broadcast_mlp
[rank0]:     return PAB_MANAGER.if_skip_mlp(timestep, count, block_idx, all_timesteps, is_temporal)
[rank0]:   File "/data1/VideoSys/videosys/core/pab_mgr.py", line 127, in if_skip_mlp
[rank0]:     is_t_in_skip_config, skip_range = self._is_t_in_skip_config(all_timesteps, timestep, cur_config)
[rank0]:   File "/data1/VideoSys/videosys/core/pab_mgr.py", line 110, in _is_t_in_skip_config
[rank0]:     index = all_timesteps.index(key)
[rank0]: ValueError: 676 is not in list

Curious how can we fix it ourselves? or will updates be coming soon to support these configs?
Thanks a lot

**Comment by oahzxl** [comment]
thanks for your feedback. this has been fixed #174

**Comment by JC1DA** [comment]
it's working now. Thanks a lot for your quick fix :+1:
