### ISSUE TITLE
Videos generated from Open Sora are mosaic

### ISSUE THREAD

**Issue by LiewFeng** [NUS-HPC-AI-Lab/VideoSys#196]
Videos generated from Open Sora Plan are normal, while videos generated from Open Sora are mossaic. Could you kindly check it again? Thanks!

**Comment by tqchen-xl** [comment]
I have the same problem

**Comment by oahzxl** [comment]
whats your env? its good on my side. please make sure diffusers verison == 0.30.0

**Comment by LiewFeng** [comment]
I tried with diffusers verison == 0.30.0 but still got the same video. By the way, which version of xformer do you use.

**Comment by LiewFeng** [comment]
The  detailed env I am using is listed as follows:
accelerate==0.33.0
aiosignal==1.3.1
annotated-types==0.7.0
antlr4-python3-runtime==4.9.3
anyio==4.4.0
attrs==24.2.0
bcrypt==4.2.0
beautifulsoup4==4.12.3
bitsandbytes==0.43.3
certifi==2024.7.4
cffi==1.17.0
cfgv==3.4.0
charset-normalizer==3.3.2
click==8.1.7
colossalai==0.4.0
contexttimer==0.3.3
contourpy==1.2.1
cryptography==43.0.0
cycler==0.12.1
decorator==5.1.1
Deprecated==1.2.14
diffusers==0.30.0
distlib==0.3.8
einops==0.8.0
exceptiongroup==1.2.2
fabric==3.2.2
fastapi==0.112.2
filelock==3.15.4
flash_attn==2.6.3
fonttools==4.53.1
frozenlist==1.4.1
fsspec==2024.6.1
ftfy==6.2.3
galore-torch==1.0
google==3.0.0
h11==0.14.0
huggingface-hub==0.24.6
identify==2.6.0
idna==3.8
imageio==2.35.1
imageio-ffmpeg==0.5.1
importlib_metadata==8.4.0
invoke==2.2.0
Jinja2==3.1.4
jsonschema==4.23.0
jsonschema-specifications==2023.12.1
kiwisolver==1.4.5
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib==3.9.2
mdurl==0.1.2
mpmath==1.3.0
msgpack==1.0.8
networkx==3.3
ninja==1.11.1.1
nodeenv==1.9.1
numpy==1.26.4
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==9.1.0.70
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.20.5
nvidia-nvjitlink-cu12==12.6.20
nvidia-nvtx-cu12==12.1.105
omegaconf==2.3.0
packaging==24.1
paramiko==3.4.1
peft==0.12.0
pillow==10.4.0
platformdirs==4.2.2
plumbum==1.8.3
pre-commit==3.8.0
protobuf==5.27.3
psutil==6.0.0
pycparser==2.22
pydantic==2.8.2
pydantic_core==2.20.1
Pygments==2.18.0
PyNaCl==1.5.0
pyparsing==3.1.4
python-dateutil==2.9.0.post0
PyYAML==6.0.2
ray==2.34.0
referencing==0.35.1
regex==2024.7.24
requests==2.32.3
rich==13.7.1
rotary-embedding-torch==0.7.0
rpds-py==0.20.0
rpyc==6.0.0
safetensors==0.4.4
sentencepiece==0.2.0
six==1.16.0
sniffio==1.3.1
soupsieve==2.6
starlette==0.38.2
sympy==1.13.2
timm==1.0.8
tokenizers==0.15.2
torch==2.4.0
torchaudio==2.4.0
torchvision==0.19.0
tqdm==4.66.5
transformers==4.39.3
triton==3.0.0
typing_extensions==4.12.2
urllib3==2.2.2
uvicorn==0.29.0
# Editable install with no version control (videosys==2.0.0)
-e /mnt/workspace/liufeng/VideoSys-master
virtualenv==20.26.3
wcwidth==0.2.13
wrapt==1.16.0
xformers==0.0.27.post2
zipp==3.20.0

**Comment by oahzxl** [comment]
i have tested on your env but still generate reasonable results. and i remove xformers dependency in latest commit #198 . can you try again? if still fail, can you provide more detailed information e.g. code, command, gpu, cuda version

**Comment by LiewFeng** [comment]
With the latest code, a new env and without any modification of the code, I still can't get resonable videos.
The command: python experiments/opensora.py
The GPU: NVIDIA A800-SXM4-80GB
The CUDA version: V12.1.105
The new env:
accelerate==0.34.2
aiosignal==1.3.1
annotated-types==0.7.0
antlr4-python3-runtime==4.9.3
anyio==4.4.0
attrs==24.2.0
bcrypt==4.2.0
beautifulsoup4==4.12.3
bitsandbytes==0.43.3
certifi==2024.8.30
cffi==1.17.1
cfgv==3.4.0
charset-normalizer==3.3.2
click==8.1.7
colossalai==0.4.0
contexttimer==0.3.3
contourpy==1.3.0
cryptography==43.0.1
cycler==0.12.1
decorator==5.1.1
Deprecated==1.2.14
diffusers==0.30.0
distlib==0.3.8
einops==0.8.0
exceptiongroup==1.2.2
fabric==3.2.2
fastapi==0.114.0
filelock==3.16.0
fonttools==4.53.1
frozenlist==1.4.1
fsspec==2024.9.0
ftfy==6.2.3
galore-torch==1.0
google==3.0.0
h11==0.14.0
huggingface-hub==0.24.6
identify==2.6.0
idna==3.8
imageio==2.35.1
imageio-ffmpeg==0.5.1
importlib_metadata==8.4.0
invoke==2.2.0
Jinja2==3.1.4
jsonschema==4.23.0
jsonschema-specifications==2023.12.1
kiwisolver==1.4.7
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib==3.9.2
mdurl==0.1.2
mpmath==1.3.0
msgpack==1.0.8
networkx==3.3
ninja==1.11.1.1
nodeenv==1.9.1
numpy==1.24.0
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.19.3
nvidia-nvjitlink-cu12==12.6.68
nvidia-nvtx-cu12==12.1.105
omegaconf==2.3.0
packaging==24.1
paramiko==3.4.1
peft==0.12.0
pillow==10.4.0
platformdirs==4.3.2
plumbum==1.8.3
pre-commit==3.8.0
protobuf==5.28.0
psutil==6.0.0
pycparser==2.22
pydantic==2.9.0
pydantic_core==2.23.2
Pygments==2.18.0
PyNaCl==1.5.0
pyparsing==3.1.4
python-dateutil==2.9.0.post0
PyYAML==6.0.2
ray==2.35.0
referencing==0.35.1
regex==2024.7.24
requests==2.32.3
rich==13.8.0
rotary-embedding-torch==0.8.3
rpds-py==0.20.0
rpyc==6.0.0
safetensors==0.4.5
sentencepiece==0.2.0
six==1.16.0
sniffio==1.3.1
soupsieve==2.6
starlette==0.38.5
sympy==1.13.2
timm==1.0.9
tokenizers==0.15.2
torch==2.2.2
torchvision==0.17.2
tqdm==4.66.5
transformers==4.39.3
triton==2.2.0
typing_extensions==4.12.2
tzdata==2024.1
urllib3==2.2.2
uvicorn==0.29.0
# Editable install with no version control (videosys==2.0.0)
-e /mnt/workspace/liufeng/VideoSys-master
virtualenv==20.26.4
wcwidth==0.2.13
wrapt==1.16.0
zipp==3.20.1

**Comment by Lexarymade** [comment]
I did not modify any code but get this result after running the samply.py
![image](https://github.com/user-attachments/assets/3abce3ab-13f5-42ce-b96f-e9c96a604c19)

**Comment by LiewFeng** [comment]
I get the same video as the above for Open Sora while I can get reasonable videos for Open Sora Plan and Latte.

**Comment by zxgx** [comment]
> With the latest code, a new env and without any modification of the code, I still can't get resonable videos. The command: python experiments/opensora.py The GPU: NVIDIA A800-SXM4-80GB The CUDA version: V12.1.105 The new env: accelerate==0.34.2 aiosignal==1.3.1 annotated-types==0.7.0 antlr4-python3-runtime==4.9.3 anyio==4.4.0 attrs==24.2.0 bcrypt==4.2.0 beautifulsoup4==4.12.3 bitsandbytes==0.43.3 certifi==2024.8.30 cffi==1.17.1 cfgv==3.4.0 charset-normalizer==3.3.2 click==8.1.7 colossalai==0.4.0 contexttimer==0.3.3 contourpy==1.3.0 cryptography==43.0.1 cycler==0.12.1 decorator==5.1.1 Deprecated==1.2.14 diffusers==0.30.0 distlib==0.3.8 einops==0.8.0 exceptiongroup==1.2.2 fabric==3.2.2 fastapi==0.114.0 filelock==3.16.0 fonttools==4.53.1 frozenlist==1.4.1 fsspec==2024.9.0 ftfy==6.2.3 galore-torch==1.0 google==3.0.0 h11==0.14.0 huggingface-hub==0.24.6 identify==2.6.0 idna==3.8 imageio==2.35.1 imageio-ffmpeg==0.5.1 importlib_metadata==8.4.0 invoke==2.2.0 Jinja2==3.1.4 jsonschema==4.23.0 jsonschema-specifications==2023.12.1 kiwisolver==1.4.7 markdown-it-py==3.0.0 MarkupSafe==2.1.5 matplotlib==3.9.2 mdurl==0.1.2 mpmath==1.3.0 msgpack==1.0.8 networkx==3.3 ninja==1.11.1.1 nodeenv==1.9.1 numpy==1.24.0 nvidia-cublas-cu12==12.1.3.1 nvidia-cuda-cupti-cu12==12.1.105 nvidia-cuda-nvrtc-cu12==12.1.105 nvidia-cuda-runtime-cu12==12.1.105 nvidia-cudnn-cu12==8.9.2.26 nvidia-cufft-cu12==11.0.2.54 nvidia-curand-cu12==10.3.2.106 nvidia-cusolver-cu12==11.4.5.107 nvidia-cusparse-cu12==12.1.0.106 nvidia-nccl-cu12==2.19.3 nvidia-nvjitlink-cu12==12.6.68 nvidia-nvtx-cu12==12.1.105 omegaconf==2.3.0 packaging==24.1 paramiko==3.4.1 peft==0.12.0 pillow==10.4.0 platformdirs==4.3.2 plumbum==1.8.3 pre-commit==3.8.0 protobuf==5.28.0 psutil==6.0.0 pycparser==2.22 pydantic==2.9.0 pydantic_core==2.23.2 Pygments==2.18.0 PyNaCl==1.5.0 pyparsing==3.1.4 python-dateutil==2.9.0.post0 PyYAML==6.0.2 ray==2.35.0 referencing==0.35.1 regex==2024.7.24 requests==2.32.3 rich==13.8.0 rotary-embedding-torch==0.8.3 rpds-py==0.20.0 rpyc==6.0.0 safetensors==0.4.5 sentencepiece==0.2.0 six==1.16.0 sniffio==1.3.1 soupsieve==2.6 starlette==0.38.5 sympy==1.13.2 timm==1.0.9 tokenizers==0.15.2 torch==2.2.2 torchvision==0.17.2 tqdm==4.66.5 transformers==4.39.3 triton==2.2.0 typing_extensions==4.12.2 tzdata==2024.1 urllib3==2.2.2 uvicorn==0.29.0
> 
> # Editable install with no version control (videosys==2.0.0)
> -e /mnt/workspace/liufeng/VideoSys-master virtualenv==20.26.4 wcwidth==0.2.13 wrapt==1.16.0 zipp==3.20.1

Hi, I double checked the example, and it shows correct result. 
<img width="608" alt="3584b657b9aa670f77def97bd97567c" src="https://github.com/user-attachments/assets/c6b2190c-6378-43cf-b9de-e10b1dfc3898">

I noticed that some of your libs have different versions. Would you please try a new env from requirements.txt?

**Comment by LiewFeng** [comment]
> i guess maybe it will be related with a800?

It works well for Open Sora in OpenDiT with A800.

**Comment by LiewFeng** [comment]
> > With the latest code, a new env and without any modification of the code, I still can't get resonable videos. The command: python experiments/opensora.py The GPU: NVIDIA A800-SXM4-80GB The CUDA version: V12.1.105 The new env: accelerate==0.34.2 aiosignal==1.3.1 annotated-types==0.7.0 antlr4-python3-runtime==4.9.3 anyio==4.4.0 attrs==24.2.0 bcrypt==4.2.0 beautifulsoup4==4.12.3 bitsandbytes==0.43.3 certifi==2024.8.30 cffi==1.17.1 cfgv==3.4.0 charset-normalizer==3.3.2 click==8.1.7 colossalai==0.4.0 contexttimer==0.3.3 contourpy==1.3.0 cryptography==43.0.1 cycler==0.12.1 decorator==5.1.1 Deprecated==1.2.14 diffusers==0.30.0 distlib==0.3.8 einops==0.8.0 exceptiongroup==1.2.2 fabric==3.2.2 fastapi==0.114.0 filelock==3.16.0 fonttools==4.53.1 frozenlist==1.4.1 fsspec==2024.9.0 ftfy==6.2.3 galore-torch==1.0 google==3.0.0 h11==0.14.0 huggingface-hub==0.24.6 identify==2.6.0 idna==3.8 imageio==2.35.1 imageio-ffmpeg==0.5.1 importlib_metadata==8.4.0 invoke==2.2.0 Jinja2==3.1.4 jsonschema==4.23.0 jsonschema-specifications==2023.12.1 kiwisolver==1.4.7 markdown-it-py==3.0.0 MarkupSafe==2.1.5 matplotlib==3.9.2 mdurl==0.1.2 mpmath==1.3.0 msgpack==1.0.8 networkx==3.3 ninja==1.11.1.1 nodeenv==1.9.1 numpy==1.24.0 nvidia-cublas-cu12==12.1.3.1 nvidia-cuda-cupti-cu12==12.1.105 nvidia-cuda-nvrtc-cu12==12.1.105 nvidia-cuda-runtime-cu12==12.1.105 nvidia-cudnn-cu12==8.9.2.26 nvidia-cufft-cu12==11.0.2.54 nvidia-curand-cu12==10.3.2.106 nvidia-cusolver-cu12==11.4.5.107 nvidia-cusparse-cu12==12.1.0.106 nvidia-nccl-cu12==2.19.3 nvidia-nvjitlink-cu12==12.6.68 nvidia-nvtx-cu12==12.1.105 omegaconf==2.3.0 packaging==24.1 paramiko==3.4.1 peft==0.12.0 pillow==10.4.0 platformdirs==4.3.2 plumbum==1.8.3 pre-commit==3.8.0 protobuf==5.28.0 psutil==6.0.0 pycparser==2.22 pydantic==2.9.0 pydantic_core==2.23.2 Pygments==2.18.0 PyNaCl==1.5.0 pyparsing==3.1.4 python-dateutil==2.9.0.post0 PyYAML==6.0.2 ray==2.35.0 referencing==0.35.1 regex==2024.7.24 requests==2.32.3 rich==13.8.0 rotary-embedding-torch==0.8.3 rpds-py==0.20.0 rpyc==6.0.0 safetensors==0.4.5 sentencepiece==0.2.0 six==1.16.0 sniffio==1.3.1 soupsieve==2.6 starlette==0.38.5 sympy==1.13.2 timm==1.0.9 tokenizers==0.15.2 torch==2.2.2 torchvision==0.17.2 tqdm==4.66.5 transformers==4.39.3 triton==2.2.0 typing_extensions==4.12.2 tzdata==2024.1 urllib3==2.2.2 uvicorn==0.29.0
> > # Editable install with no version control (videosys==2.0.0)
> > -e /mnt/workspace/liufeng/VideoSys-master virtualenv==20.26.4 wcwidth==0.2.13 wrapt==1.16.0 zipp==3.20.1
> 
> Hi, I double checked the example, and it shows correct result. <img alt="3584b657b9aa670f77def97bd97567c" width="608" src="https://private-user-images.githubusercontent.com/34452939/365565852-c6b2190c-6378-43cf-b9de-e10b1dfc3898.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NzA0MTEsIm5iZiI6MTcyNTg3MDExMSwicGF0aCI6Ii8zNDQ1MjkzOS8zNjU1NjU4NTItYzZiMjE5MGMtNjM3OC00M2NmLWI5ZGUtZTEwYjFkZmMzODk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDA4MjE1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwNmZkOGU3YjVhNzQxYmJhYTQ3ZTUyMTg3YWYyZWE4ZWRkYTlhMTdkNzU5ZWUzYjdlZDI1OTk2Y2M3YWY0MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SrFN4O_6etbXx7-_WJwmX0YeJRddTXAjCb0mhK8I3aI">
> 
> I noticed that some of your libs have different versions. Would you please try a new env from requirements.txt?

I install the env following the instructions in the README and the requirements.txt seems don't specify the version of software. Could you kindly provide a more detailed requirements.txt? It can be obtained with `pip freeze > requirements.txt`

**Comment by Lexarymade** [comment]
> i guess maybe it will be related with a800?

the original open sora works well in h100, but the videosys version failed.

**Comment by LiewFeng** [comment]
> > i guess maybe it will be related with a800?
> 
> the original open sora worked well in h100, but the videosys version failed.

The original Open Sora also works well on A800.

**Comment by oahzxl** [comment]
could you try whether fp32 will also generate mosaic? usage is: 
```
engine = VideoSysEngine(config, dtype=torch.float)
```

**Comment by oahzxl** [comment]
hi, we create a wechat group to solve this problem. welcome to join

![IMG_7702](https://github.com/user-attachments/assets/151e832d-610d-474e-ac76-65406b7fd439)

**Comment by oahzxl** [comment]
fixed #202
