### ISSUE TITLE
Linking the gradio app on readme

### ISSUE THREAD

**Issue by yvrjsharma** [NUS-HPC-AI-Lab/VideoSys#214]
[KoolCogVideoX](https://huggingface.co/spaces/bertjiazheng/KoolCogVideoX) is mind-blowing. Congratulations on the release! 

Any plans to include a link to the [local gradio repo](https://github.com/NUS-HPC-AI-Lab/VideoSys/blob/master/gradio/cogvideox.py) in the project readme, along with instructions on how to run it? 

For example, the CogVideoX repo links the gradio app in their readme here: https://github.com/THUDM/CogVideo?tab=readme-ov-file#inference

**Comment by oahzxl** [comment]
yeah, thats a good suggestion! will update in future!

**Comment by oahzxl** [comment]
this issue has been solved in pr #220
