### ISSUE TITLE
What's the plan for supporting Open-Sora-Plan v1.2.0

### ISSUE THREAD

**Issue by littletomatodonkey** [NUS-HPC-AI-Lab/VideoSys#215]
Hi, thanks for your great job! I was wondering that what's your plan about supporting Open-Sora-Plan v1.2.0? thanks!

**Comment by oahzxl** [comment]
i think it will be in 1~2 weeks

**Comment by littletomatodonkey** [comment]
thanks for your so quick response! Looking forward to it.

**Comment by littletomatodonkey** [comment]
I saw mode details about v1.2.0 and DSP, it seems that DSP can not support v1.2.0's model seq-parallel inference since multi-dim transformer block is not used in v1.2.0, do you have any ideas? Thanks!

**Comment by oahzxl** [comment]
yeah you are right, we will use ulysses for open sora plan v1.2 as in cogvideo
