### ISSUE TITLE
multi-gpu test for Opensora-plan v1.2

### ISSUE THREAD

**Issue by LWang1016** [NUS-HPC-AI-Lab/VideoSys#230]
@gttiankai  Hi, thanks very much for your great work. 
Does the repo currently support the opensora-plan v1.2 with multi-gpus testing?

Currently, When I test the opensora-plan v1.2 with multi-gpus, it raised below error:

RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[10/28/24 13:49:34] ERROR    VideoSys - ERROR: Worker VideoSysWorkerProcess pid 294884 died, exit code: -6
                    INFO     VideoSys - INFO: Killing local worker processes

Do you have some ideas?  Thx very much!

**Comment by zhaosuisui** [comment]
I have the same problem!
