### ISSUE TITLE
Pyramid Attention Broadcast (PAB) -- Attention Analysis

### ISSUE THREAD

**Issue by agneet42** [NUS-HPC-AI-Lab/VideoSys#231]
Hi,

Thanks for the great work on PAB. I was wondering if there is a script that you had used to analyze the attention patterns in the DiT layers. Would it be possible to point me to them, if they are available?

Thanks!

**Comment by oahzxl** [comment]
sadly they have been deleted. its very simple, just store outputs and calculate mse loss between previous outputs and current

**Comment by agneet42** [comment]
thanks!
so essentially the MSE across two layers here in case of Latte, for example : https://github.com/NUS-HPC-AI-Lab/VideoSys/blob/master/videosys/models/transformers/latte_transformer_3d.py#L410

**Comment by oahzxl** [comment]
yeah

**Comment by agneet42** [comment]
@oahzxl qq - do you do thisfor each layer, for each step, or do you only take the output from the last layer for each step?

**Comment by agneet42** [comment]
I think you average it across each layer -- per the paper. 
Have you noticed the same attention pattern in newer models such as CogVideoX?

**Comment by oahzxl** [comment]
yeah i average them. i havent do such exp on cogvideo. but it works good.
