### ISSUE TITLE
colossalai 0.4.6 requires diffusers==0.29.0, but Videosys have diffusers 0.30.0 which is incompatible.

### ISSUE THREAD

**Issue by LukeLIN-web** [NUS-HPC-AI-Lab/VideoSys#238]
videosys 2.0.0 requires diffusers==0.30.0, but you have diffusers 0.29.0 which is incompatible.

**Comment by oahzxl** [comment]
install colossalai without dependency: `pip install --no-deps colossalai `. we already do this in setup.py

**Comment by LukeLIN-web** [comment]
Thank you!
