### ISSUE TITLE
[Question] Do you compare FastSeq with RingAttention or Context Parallel in TransformerEngine?

### ISSUE THREAD

**Issue by baoleai** [NUS-HPC-AI-Lab/VideoSys#58]
This is an impressive project! It demonstrates superior performance compared to Ulysses. Have you also conducted comparisons of FastSeq with RingAttention or Context Parallel in the TransformerEngine?

**Comment by oahzxl** [comment]
We will be updating our resuilts with more baselines soon

**Comment by oahzxl** [comment]
close due to outdated
