### ISSUE TITLE
HF Hub integration for easy model download and upload

### ISSUE THREAD

**Issue by sayakpaul** [NUS-HPC-AI-Lab/VideoSys#61]
Hello there 👋

Amazing work here. I think it's definitely going to improve the ecosystem around training diffusion transformers more efficiently. Especially, folks that are interested in doing SoRA-like training, this codebase is going to be immensely helpful! 

My name is Sayak, an ML Engineer at HF. I noticed that the weights are currently kept on Google Drive. I wanted to know if you would be open to integrating support for using the HF Hub platform for sharing the models and also for model loading. I am happy to open a PR for that :) 

Cc: @LysandreJik

**Comment by oahzxl** [comment]
sure, we are very intereted in that

**Comment by sayakpaul** [comment]
Will open a PR soon!

**Comment by bhack** [comment]
NIce initative @sayakpaul are you planning to have also some discriminative tasks heads on HF?
