### ISSUE TITLE
WeChat Group and Discord Server

### ISSUE THREAD

**Issue by KKZ20** [NUS-HPC-AI-Lab/VideoSys#66]
Hi everyone! We have created a [WeChat group](https://github.com/NUS-HPC-AI-Lab/OpenDiT/blob/master/figure/wechat.jpg) and [Discord server](https://discord.gg/yXF4n8Et) to facilitate better feedback on using Opendit and to discuss the latest technologies. Feel free to join it!

**Comment by kabachuha** [comment]
Hi! I'm using this Discord link, but it says it is either incorrect or the invite has expired

**Comment by KKZ20** [comment]
The discord invitation has been updated. Thanks!
