### ISSUE TITLE
About FlashAttention

### ISSUE THREAD

**Issue by ZekaiGalaxy** [NUS-HPC-AI-Lab/VideoSys#69]
Thank you for your great work :) !

Here is my question: I tried to follow the instructions but failed in the flash-attention related steps. According to [this issue](https://github.com/Dao-AILab/flash-attention/issues/148), V100 are not supported.

So I wonder the efficiency gain without the flash-attention module, or are there any methods to surpass the above issue and achieve comparable performance on V100s?

Thank you!

**Comment by bhack** [comment]
Can I ask you why you are still using the external flash attention?
`torch.nn.functional.scaled_dot_product_attention` has already a flashattention-2 implementation:
https://pytorch.org/docs/2.2/generated/torch.nn.functional.scaled_dot_product_attention.html

**Comment by oahzxl** [comment]
its implemtation sometimes is slower than flashattn on device < H100

**Comment by bhack** [comment]
Probably we could monitor this
https://github.com/pytorch/pytorch/pull/120642
