### ISSUE TITLE
When running CIFAR10 demo, NAN appears in loss.

### ISSUE THREAD

**Issue by fupiao1998** [NUS-HPC-AI-Lab/VideoSys#74]
Hello, I am running the CIFAR10 demo you provided. The script used is as follows. I found that the loss cannot be optimized and NAN appears. Is there any solution to this problem?
```
torchrun --standalone --nproc_per_node=8 train.py \
    --model DiT-XL/2 \
    --batch_size 36 \
    --mixed_precision fp16 \
    --ckpt_every 10000\
    --num_workers 12 \
    --enable_modulate_kernel \
    --enable_layernorm_kernel \
    --enable_flashattn
```
![image](https://github.com/NUS-HPC-AI-Lab/OpenDiT/assets/38381312/d91665cb-2c48-4d7b-b3e5-6f8293048dde)

**Comment by oahzxl** [comment]
you can use bf16 for mix precision toavoid nan

**Comment by fupiao1998** [comment]
Thank you so much for such a quick reply, I will try your solution, thank you!

**Comment by fupiao1998** [comment]
Hello, after I replaced it with bf16, the NAN problem still occurred.
```
torchrun --standalone --nproc_per_node=8 train.py \
    --model DiT-XL/2 \
    --batch_size 36 \
    --ckpt_every 10000\
    --num_workers 12 \
    --enable_modulate_kernel \
    --enable_layernorm_kernel \
    --enable_flashattn \
    --mixed_precision bf16 
```
![image](https://github.com/NUS-HPC-AI-Lab/OpenDiT/assets/38381312/79ff140e-6374-49ac-a6bd-b142d1402d16)

**Comment by oahzxl** [comment]
thats strange. are you training on imagenet?
we have not met such problem. here are some potential solutions but not sure: 1) increase batch size 2) decrease grad_clip 3) disable modulate kernel 4) use grad accumulation

**Comment by oahzxl** [comment]
ok im trying to reproduce your result

**Comment by fupiao1998** [comment]
Thank you so much!

**Comment by oahzxl** [comment]
i have not yet reproduced your result but i suspect the nan is brought by class embedding. class num is set to 1000 as imagenet by default. but in cifar10, it only has 10 classes. so as the train continues, the prob of other 990 classes will be really small and cause this nan

**Comment by fupiao1998** [comment]
OK, I will try again after modifying it, thank you.
In addition, I checked the log and found that NAN will appear at epoch=5 during my training process.

**Comment by MikeChenfu** [comment]
I got the same problem when enable modulate kernel.

**Comment by SmileTAT** [comment]
> I got the same problem when enable modulate kernel.

me too

**Comment by oahzxl** [comment]
close due to outdated
